/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_avis (void);
GtkWidget* create_supprimerreclamation (void);
GtkWidget* create_reclamation (void);
GtkWidget* create_supprimer_avis (void);
GtkWidget* create_choisir (void);
GtkWidget* create_message (void);
