/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *avis;
  GtkWidget *supprimerreclamation;
  GtkWidget *reclamation;
  GtkWidget *supprimer_avis;
  GtkWidget *choisir;
  //GtkWidget *message;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  avis = create_avis ();
  //gtk_widget_show (avis);
  supprimerreclamation = create_supprimerreclamation ();
  //gtk_widget_show (supprimerreclamation);
  reclamation = create_reclamation ();
  //gtk_widget_show (reclamation);
  supprimer_avis = create_supprimer_avis ();
  //gtk_widget_show (supprimer_avis);
  choisir = create_choisir ();
  gtk_widget_show (choisir);
  //message = create_message ();
  //gtk_widget_show (message);

  gtk_main ();
  return 0;
}

